### PR TITLE
Fix make build system adding DDP source, recommend CMake

### PR DESCRIPTION
**Pull request by FreyJo**
Reported here: https://discourse.acados.org/t/a-compile-error-when-run-make-examples-c/1640

minor:
- improve plot in example
- do not warn about CasADi 3.6.5

### CODE REVIEW

**Review by sandmaennchen — APPROVED** [review]

**Comment by fjiwrogno** [comment]
> Reported here: https://discourse.acados.org/t/a-compile-error-when-run-make-examples-c/1640
> 
> minor:
> 
> * improve plot in example
> * do not warn about CasADi 3.6.5

However, I still get the same problem when I try:
 `make examples_c` :
It shows the error:
`acados/lib/libacados.so: undefined reference to ocp_nlp_ddp_config_initialize_default` 
Thanks for your help.

**Comment by fuwafuwaboom** [comment]
"choose cmake **_OR_** make"

**Comment by fjiwrogno** [comment]
> "choose cmake **_OR_** make"

Thanks for your help.
The problem has been solved.

**Comment by kashifzr** [comment]
@fjiwrogno How you solve this problem.

**Comment by jluzxr** [comment]
However, I still get the same problem when I try:
`make examples_c :`
It shows more errors as follow:

微信图片_20241011112934

Thanks for your help.

**Pull request merged**
