### PR TITLE
Add list of parameters for the acados matlab interface

### PR DESCRIPTION
**Pull request by EnricaSo**
The added table contains the list of parameters with the following columns: parameter name, description, accepted values and other info such as relevant references. It is not exhaustive yet.

The best workflow to generate the table that I found for now is the following:
1) edit the shared file: https://docs.google.com/document/d/14lLBsLHhSodpI9Lhq3YMoge5dXzUjT22pmzlMGeta50/edit?usp=sharing
2) download in .docx and convert to Github-flavored markdown with pandoc
3) copy-paste to "index.md"
Any different proposal is well accepted.

### CODE REVIEW

**Comment by giaf** [comment]
@tmmsartor any progress with this PR?

**Comment by EnricaSo** [comment]
I have edited the Google doc few days ago. The references and descriptions are not complete yet, but the list of parameters should be exhaustive now. Let me know if/how I can help on this.
Cheers,
Enrica

**Comment by tmmsartor** [comment]
Hi @EnricaSo , sorry for late answer, I was trying to integrate the generated html in our read the docs based web site, but it was not looking to readable, I think the best option is to keep this "docs"  in the form of an spreadsheet for now, see #486. (It is maybe not in sync with the doc version of it)
If you want to give edit access to it to other people just ask :open_hands:

**Comment by EnricaSo** [comment]
Thank you @tmmsartor for adding the cheatsheet and the doc, it's very practical!

**Comment by FreyJo** [comment]
thanks again @EnricaSo merged in #486

**Pull request closed without merging**
