### PR TITLE
adding @giaf's API to acados_template interface

### PR DESCRIPTION
**Pull request by zanellia**
Adding explicit setters (`ocp.dims.nx = 4` => `ocp.set('dims_nx', 4)`) to the acados_template module in order to comply to @giaf's API used in the MATLAB MEX-based interface.

### CODE REVIEW

**Comment by zanellia** [comment]
@giaf I have added a simple example using your API based on explicit setters: https://github.com/zanellia/acados/blob/giaf_api/interfaces/acados_template/examples/python/pendulum_example/generate_c_code_explicit_setters.py. Have a look ;)

**Comment by giaf** [comment]
This was the low-hanging fruit :) The setters are created automatically form the string name, right?
Next steps are more involved and require changes in the classes.

I guess this is the further it can go before sitting down together to work on it, in a couple of weeks.

**Comment by zanellia** [comment]
Yes, kind of :) What do you have in mind exactly? The classes can/should stay the same to a large degree as long as the APIs are consistent, no?

**Comment by giaf** [comment]
To sit down together and work on it in a couple of weeks ;)

**Comment by zanellia** [comment]
merge?

**Comment by giaf** [comment]
ok

**Comment by zanellia** [comment]
let's merge this before Thu? :)

**Comment by zanellia** [comment]
merging since it was already approved ;)

**Pull request merged**
