### PR TITLE
'create' facilities in ocp_qp

### PR DESCRIPTION
**Pull request by roversch**
Instead of using the old 'allocate' functions, we now offer 'create' facilities, that calculate the size of a module and allocate it all at once.

### CODE REVIEW

**Comment by roversch** [comment]
@rienq This PR removes all 'allocate' functions (rationale: better to offer only one way of doing something). Is that breaking your code?

**Comment by rienq** [comment]
By my code, you mean PR #121? This is still broken because of a minor bug somewhere that I did not have the time yet to trace but I will try to do that soon.. I would also need to make a DAE based OCP example or better even a unit test.

**Comment by dkouzoup** [comment]
Hey @rienq . I think @roversch was referring to your statement once that you use the allocate_qp function for your own projects. This pull request gets rid of this function as we discussed a few days ago.

**Comment by rienq** [comment]
Hmm, I thought this allocate functionality would still be there some way but then based on the functions that return the memory size needed to store the struct and the functions that put the pointers in place?
About my code being broken: for sure, but that's why I will probably locally not be pulling acados for a while at least until the upcoming paper deadlines ;-)

**Comment by dkouzoup** [comment]
yes of course it's there, just the syntax and the underlying memory allocation changed.

**Comment by rienq** [comment]
It looks great! :+1:

**Pull request merged**
