### PR TITLE
Add qpOASES as a submodule

### PR DESCRIPTION
**Pull request by bnovoselnik**
Changes made:

- fixed issue #138 
- qpOASES is now a git submodule as other external libraries

### CODE REVIEW

**Comment by dkouzoup** [comment]
@bnovoselnik try to fix travis for this PR

**Comment by bnovoselnik** [comment]
Yep, Travis is failing because ACADOS interface to qpOASES needs to be patched as well.
This is the reason why examples that use qpOASES are currently producing segfaults.
Yuning is working on this atm.

**Comment by dkouzoup** [comment]
@bnovoselnik are you up-to-date with master? shall I merge this?

**Comment by bnovoselnik** [comment]
@dkouzoup yes, you can merge it

**Pull request merged**
