### PR TITLE
[WIP] Fixing windows examples and undefined behavior errors

### PR DESCRIPTION
**Pull request by dkouzoup**
- [x] Fix wind turbine example for windows

- [ ] Fix nonlinear chain example for windows

- [x] Fix sim wind turbine example for windows

- [ ] Fix _all_ examples for windows

- [x] Resolve undefined behavior errors in examples

### CODE REVIEW

**Comment by dkouzoup** [comment]
Sorry for bombarding with PR emails. This PR fixes a couple of mem alignment issues in acados and successfully runs two c examples on appveyor (more should be fixed asap). If it passes the tests it's ready to merge.

**Comment by roversch** [comment]
Have you also tried running with `-fsanitize=undefined` on Clang? I get quite a few warnings about undefined behavior concerning alignment etc, even before this PR. I filed an issue (#330) as well.

**Comment by dkouzoup** [comment]
Haven't yet. Will do for sure in my "free" time ;)

**Comment by zanellia** [comment]
closing this for now.

**Pull request closed without merging**
