### PR TITLE
restructured hpmpc interface

### PR DESCRIPTION
**Pull request by dkouzoup**
- fixed segfault
- avoided unnecessary copying of data
- using assign_memory properly
- broke partial tightening (to be fixed by @zanellia)

### CODE REVIEW

**Comment by giaf** [comment]
When do you want to merge? Now or only after Andrea fixes partial tightening?

**Comment by dkouzoup** [comment]
I'd leave @zanellia to decide. In principle there is quite some cleanup needed to have partial tightening working in a proper way so maybe it's better to remove it and directly implement it as a separate module based on hpipm?

**Comment by zanellia** [comment]
It might be a good idea to have an implementation in hpmpc until we start
implementing this in hpipm. I can revive it in little time without
polluting too much the polished interface ;)

On Mon, Mar 5, 2018 at 9:05 AM, Dimitris Kouzoupis <notifications@github.com

**Comment by dkouzoup** [comment]
Sounds good! Let's try today maybe since big merges are on their way ;)

**Comment by dkouzoup** [comment]
@zanellia  status on this one? We should merge probably before merging with giaf_new_core, and the latter has to happen asap..

**Comment by zanellia** [comment]
I am on it ;) We should merge https://github.com/dkouzoup/acados/pull/2 first.

**Comment by dkouzoup** [comment]
addressed in 3561aafcdd8eab8331dfecbb8f1c5c506beb7912

**Pull request closed without merging**
