### PR TITLE
templates: Rename library to follow linux conventions

### PR DESCRIPTION
**Pull request by tmmsartor**

### CODE REVIEW

**Comment by giaf** [comment]
That's not just linux convention... ;)

**Comment by zanellia** [comment]
Thanks @tmmsartor! Although, I guess this has broken the other examples using the template engine :P

**Comment by zanellia** [comment]
actually not, it all works fine!

**Comment by tmmsartor** [comment]
The name of the library file was used only in the generate_solver.py script inside the interface module, at least from my quick check, I didn't check the matlab version.

**Pull request merged**
