### PR TITLE
Mex windows doc and env setup script

### PR DESCRIPTION
**Pull request by jkoendev**
* Setting up the environment variable on Windows with a Matlab script.
* Some documentation in the `README.md` on how to run examples on Windows.

### CODE REVIEW

**Comment by jkoendev** [comment]
Can be reviewed @giaf

**Comment by FreyJo** [comment]
I think we should put a higher priority on documentation within the `docs` folder than local readme files, since the [docs.acados.org](docs.acados.org) webpage is generated through that, can be googled etc.
Thus, I suggest to include the information there.

**Comment by jkoendev** [comment]
you are right, i was just not very familiar with the doxygen stuff yet. I just found this Markdown file which might be the appropriate place:
https://github.com/acados/acados/blob/master/docs/interfaces/index.md

This PR is more like a shortterm solution to set-up the path on windows, i didn't want to touch the Linux part for now. I think we should seek a more permanent solution in the long run for both operation systems, see also #407

**Comment by giaf** [comment]
Agree. But it is also good to have this information in local readme files, that is the right information in the right place.

**Pull request merged**
