### PR TITLE
Lifted integrators based on Yutao's integrators - WIP

### PR DESCRIPTION
**Pull request by zanellia**

### CODE REVIEW

**Comment by zanellia** [comment]
I have fixed a big that caused the SQP iterations to converge to an inaccurate solution. I guess we could merge @giaf?

**Comment by giaf** [comment]
Two questions:
1) what was the bug in the lifted IRK?
2) in update_vectors, I deleted these lines on purpose after fixing HPIPM. So either you forgot to submodule update, or I forgot to push HPIPM in acados ;)

**Comment by dkouzoup** [comment]
2. is not a question :P

**Comment by giaf** [comment]
the question is, what happened?

**Pull request merged**
