### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by josipkh**
This PR addresses some of the points listed in #1140 (and others) and updates the documentation in several places.

### CODE REVIEW

**Comment by josipkh** [comment]
Hi Jonathan,
thanks for checking!
Yes, I would like to finish updating the problem formulation pdf with a few more things related to the initial state...
I was hoping to do it by now, but some other things came up so I plan to finish it by the end of the week.
I will mark the PR as ready then, hope that's ok :)

**Comment by josipkh** [comment]
Hello,
I made a few more changes and marked the PR as ready.
There is two more things I wanted to ask about:
- are there any changes you would suggest for the [MATLAB examples readme](https://github.com/acados/acados/blob/master/examples/acados_matlab_octave/README.md)? maybe even removing it altogether (Python interface doesn't have one)
- perhaps adding a note about the environment setup as suggested in #565 would be nice, but I am not sure where is the best place to do so (I mainly use Windows, where I edit MATLAB's `startup.m` script)

**Comment by FreyJo** [comment]
Hi Josip,
thanks for raising those points.
I addressed them in the last two commits here.
If you agree, I would merge this now.

**Comment by josipkh** [comment]
Thanks for the quick update!
Feel free to merge from my side :)

**Pull request merged**
