### PR TITLE
revived hpmpc interface 

### PR DESCRIPTION
**Pull request by zanellia**
revived (basic) hpmpc interface - still needs some polishing.

### CODE REVIEW

**Comment by dkouzoup** [comment]
Hey Andrea,

I fetched your PR locally, merged with latest new_core but output of HPMPC example is:

 acados + hpmpc



Test problem: mass-spring system with 4 masses and 3 controls.

MPC problem size: 8 states, 3 inputs, 15 horizon length, 11 two-sided box constraints, 0 two-sided general constraints.

acados_return = 0
u =
 -0.27498  -0.50000  -0.50000

  0.50000   0.50000  -0.50000

  0.50000   0.50000  -0.50000

  0.50000   0.50000  -0.50000

  0.50000   0.15350   0.50000

  0.01523  -0.18903   0.50000

 -0.50000  -0.11373   0.50000

 -0.50000   0.04608   0.17908

 -0.50000  -0.00039   0.14181

 -0.50000  -0.24397   0.50000

 -0.17375  -0.42847   0.50000

  0.06401  -0.31773   0.50000

  0.10362   0.05127  -0.01150

  0.03675   0.33262  -0.50000

 -0.03703   0.08591  -0.50000


x =


  2.25977   2.23829   0.33222   0.10497  -1.23436  -1.29495   0.95959   0.13887

  1.54999   1.56983   0.98843   0.30509  -1.83368  -1.57072   1.21501   0.39213

  0.65261   0.91911   1.55185   0.65282  -1.95165  -1.25078   0.61816   0.69664

 -0.15323   0.51673   1.68381   1.10936  -1.46172  -0.64813  -0.40777   0.77234

 -0.57773   0.36004   1.44981   1.48885  -0.46960  -0.30814  -0.76970   0.37031

 -0.51644   0.29187   1.12702   1.55914   0.40720  -0.27526  -0.76688  -0.41991

 -0.13626   0.24992   0.86710   1.21237   0.75442  -0.17520  -0.56205  -1.22236

  0.31025   0.30587   0.66677   0.55239   0.66964   0.11063  -0.55682  -1.61500

  0.62332   0.49943   0.44088  -0.15423   0.25477   0.33855  -0.65224  -1.40330

  0.69697   0.72225   0.21693  -0.62230  -0.24521   0.20251  -0.52660  -0.70078

  0.58437   0.78322   0.08600  -0.67914  -0.47261  -0.28958  -0.27468   0.18029

  0.41974   0.59004   0.10978  -0.32756  -0.46612  -0.76263   0.07927   0.87729

  0.27143   0.25975   0.25257   0.26881  -0.42181  -0.80349   0.19034   1.12837

  0.13299   0.02455   0.38941   0.85562  -0.42021  -0.39799   0.06372   0.84012

  0.00000   0.00000   0.47763   1.18344  -0.38305   0.00000  -0.00000   0.13181


lam =
  0.00000   2.76659   9.76796   0.00000   0.00000   0.00000

  0.00000   0.00000  10.94195   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.63034   0.11624   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   7.23851   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   2.93984   1.68584   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   1.35317   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   2.56475   0.76560   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.99247   0.00000   1.028210.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   2.212990.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.55636   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.905460.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  1.28124   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  1.02829   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.18386   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.688680.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   2.084140.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.672530.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   2.77802   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   5.40210   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.000000.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000

  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 18072.01557 18571.30567 18354.52442 19919.93243   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 18071.97005 18571.94789 18346.30489 19933.16516


N ITER = 10

**Comment by dkouzoup** [comment]
If you fixed the bug, can you update the example to return the correct solution? Branimir also implemented checks for the KKT tolerance (see other examples). Cheers

**Comment by dkouzoup** [comment]
Another issue: ocp_qp_hpmpc_calculate_memory_size should _not_ take qp_in as input. Only dims and args. I see that hpmpc needs idxb, but in priniciple it is required to calculate nbb and ngg for partial condensing which can be also inferred from nbx/nbu (even easier than from hidxb), that exist in dims. If the signature of the functions are not the same, we cannot use hpmpc as a QP solver in the NLP solvers.

**Comment by zanellia** [comment]
I have merged and fixed the example to return the same result. I will have
to fix the interface and look into the residual computation later.

Cheers,
Andrea

**Comment by dkouzoup** [comment]
To minimize changes in HPMPC I think we only need new (perhaps duplicate with a slightly different name?) functions:

hpmpc_d_ip_ocp_hard_tv_work_space_size_bytes
d_part_cond_compute_problem_size (called from the function above)

with nbx/nbu instead of idxb as inputs. Some other functions with idxb as arguments inside the first one, don't use idxb and we can pass NULL pointer I believe. Maybe @giaf can confirm at some point.

**Comment by dkouzoup** [comment]
@zanellia  we added the routines in HPMPC with @giaf. See:

https://github.com/giaf/hpmpc/commit/fc8b4246471959cd1eafea04e53b971b5246429f

I will try them asap.

**Comment by zanellia** [comment]
@dkouzoup I have checked out the pull request on a fresh clone and the result seems to be fine on my machine:


 acados + hpmpc



Test problem: mass-spring system with 4 masses and 3 controls.

MPC problem size: 8 states, 3 inputs, 15 horizon length, 11 two-sided box constraints, 0 two-sided general constraints.

acados_return = 0
u = 
  0.15628  -0.50000  -0.50000 

  0.50000   0.25104  -0.50000 

  0.50000   0.50000  -0.50000 

  0.50000   0.50000  -0.50000 

  0.44451   0.24117   0.37760 

 -0.50000  -0.09564   0.50000 

 -0.50000  -0.41852   0.50000 

 -0.50000  -0.50000   0.50000 

 -0.50000  -0.50000   0.07795 

 -0.03428  -0.50000  -0.14751 

  0.46242  -0.48625  -0.21165 

  0.46290   0.36588  -0.27748 

  0.20018   0.50000  -0.37693 

 -0.02678   0.50000  -0.43103 

 -0.07684   0.40256  -0.34863 


x = 


  2.31148   2.23937   0.33223   0.10497  -1.03615  -1.28640   0.95970   0.13887 

  1.68020   1.55460   0.98834   0.30509  -1.73250  -1.63511   1.21308   0.39214 

  0.79540   0.89476   1.54821   0.65273  -2.00539  -1.22057   0.60574   0.69597 

 -0.07123   0.52667   1.67343   1.10827  -1.63799  -0.55272  -0.41833   0.76859 

 -0.59964   0.42611   1.42555   1.48463  -0.68669  -0.19848  -0.80781   0.36090 

 -0.68477   0.39238   1.10013   1.54825   0.06617  -0.26559  -0.73640  -0.43631 

 -0.41048   0.26611   0.86943   1.19429   0.68257  -0.51440  -0.48828  -1.23103 

  0.06187   0.06635   0.73179   0.53709   0.81880  -0.52235  -0.41191  -1.59026 

  0.46131  -0.05028   0.50644  -0.14513   0.41027  -0.20951  -0.81931  -1.33435 

  0.62616   0.00715   0.04001  -0.58258  -0.06519   0.10409  -1.29998  -0.67292 

  0.60448   0.14353  -0.56964  -0.67527  -0.29769   0.06490  -1.33203  -0.02557 

  0.49666   0.25404  -1.03967  -0.51893  -0.39749   0.00941  -0.74613   0.29311 

  0.34797   0.27195  -1.10591  -0.29560  -0.46227  -0.25909   0.21280   0.26537 

  0.17439   0.15505  -0.70065  -0.12679  -0.50444  -0.46924   1.04425   0.12425 

 -0.00000  -0.00000   0.00000   0.00000  -0.46875  -0.38027   1.33773   0.12939 


lam = 
  0.00000   2.15647   8.50528   0.00000   0.00000   0.00000 

0.00000   0.00000  10.31164   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   3.65382   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   7.67247   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   4.95821   0.71128   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   2.62639   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   3.29221   0.30173   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

1.37211   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.77854   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

3.11368   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.49818   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

2.74731   0.65375   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.20150   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.94544   1.31695   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   1.17423   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.06904   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.13049   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 

0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 78127.74506 79956.39924 78282.70279 81238.94897   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000 78129.06938 79948.63613 78281.22772 81254.31281 


N ITER = 12

**Comment by zanellia** [comment]
@dkouzoup I have merged your pull request into this one and hpmpc seems to work fine. Should we merge into new_core soon?

**Comment by zanellia** [comment]
@dkouzoup this should fix the bug due to inverted upper bounds in hpmpc - let's merge tomorrow?

**Pull request merged**
