### PR TITLE
Python paths autoload

### LINKED ISSUE #517: [Python] nothing works if put outside acados source directory
Hi,
just installed acados, I'm trying to make it works with Python and CasADi.

Currently I've been able to run examples contained in `examples/acados_python/` by adding this lines in my bashrc:
```bash
export ACADOS_SOURCE_DIR=/home/flynn/sources/for_casadi/acados
export LD_LIBRARY_PATH=/home/flynn/sources/for_casadi/acados/lib:$LD_LIBRARY_PATH
```

However, when I take those directories and move them outside the acados installation path, I can't run them anymore. Here's the error (trying with pendulum_example):
```
[...]
gcc -fPIC -DACADOS_WITH_QPOASES -c acados_solver_pendulum_ode.c -I ../../../../include/blasfeo/include/ -I ../../../../include/hpipm/include/ \
-I ../../../../include -I ../../../../include/acados/ -I ../../../../include/qpOASES_e/
acados_solver_pendulum_ode.c:7:10: fatal error: acados/utils/print.h: No such file or directory
 #include "acados/utils/print.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Eventually I've found out that I need this one more line in bashrc:
```bash
export C_INCLUDE_PATH=/home/flynn/sources/for_casadi/acados/include:/home/flynn/sources/for_casadi/acados/include/blasfeo/include:/home/flynn/sources/for_casadi/acados/include/hpipm/include:/home/flynn/sources/for_casadi/acados/include/acados:/home/flynn/sources/for_casadi/acados/include/qpOASES_e:$C_INCLUDE_PATH
```

But I still can't compile successfully, encountering a linking error:
```
[...]
gcc -fPIC -DACADOS_WITH_QPOASES -shared -o libacados_solver_pendulum_ode.so  main_pendulum_ode.o pendulum_ode_model/pendulum_ode_expl_ode_fun.o pendulum_ode_model/pendulum_ode_expl_vde_forw.o lin_res_r_cost/lin_res_r_cost.c  lin_res_r_e_cost/lin_res_r_e_cost.c  acados_solver_pendulum_ode.o -L ../../../../lib \
-L ../../../../lib \
-lacados -lhpipm -lblasfeo -lqpOASES_e -lm \

/usr/bin/ld: cannot find -lacados
/usr/bin/ld: cannot find -lhpipm
/usr/bin/ld: cannot find -lblasfeo
/usr/bin/ld: cannot find -lqpOASES_e
collect2: error: ld returned 1 exit status
```

So I've tried to symbolic-link those libraries in a system directory:
```bash
cd lib
sudo ln -s `pwd`/*.so /usr/local/lib
```
and I've finally make everything run!

Using Ubuntu 18.04 with CasADi 3.5

### PR DESCRIPTION
**Pull request by Maik93**
Hi all,
I'm just approaching acados for my master thesis on MPC problems. It seems a great tool and I'd like to contribute where I can, so here's a quick code improvement regarding Python path definitions.

Hope to have done something pleasant, have a nice Holidays!

PS: this should close #517.

### CODE REVIEW

**Comment by FreyJo** [comment]
looks good to me.
@zanellia : what do you think?

**Comment by zanellia** [comment]
It's in principle alright, but we need a way to distinguish between the location of source code and libs on the host machine and their counterparts on the target (embedded) device. I can take care of cleaning this up and packaging everything into a pip package (with @tmmsartor?).

**Comment by tmmsartor** [comment]
Yes, even before having the pip, I was working with @FreyJo to [add](https://github.com/FreyJo/acados/tree/tmmsartor_sim_template) modular support for the integrators in the python interface, we are also fixing the path issue mentioned by @Maik93

**Comment by FreyJo** [comment]
These paths will be set automatically after merging #538.
I will close this PR because of that.
Nevertheless, thanks a lot for the effort @Maik93

**Pull request closed without merging**
