### PR TITLE
Merging with zanellia/stable 

### PR DESCRIPTION
**Pull request by zanellia**
Added new interface to hpmpc based on blasfeo, added interface to partial tightening hpmpc, added preliminary interface to NL-IP. Fixed a bug in test_nmpc.c, sensitivities were broken (worked on Chen example as NU=1).

### CODE REVIEW

**Comment by roversch** [comment]
Your pull request breaks the build, see
https://github.com/acados/acados/pulls

**Comment by zanellia** [comment]
Alright, I was compiling with -DCMAKE_BUILD_TYPE=Debug. Did some linting now, let's see if it works.

**Comment by roversch** [comment]
Still getting a lot of linting errors, see e.g.
https://travis-ci.org/acados/acados/jobs/194490657

**Comment by rienq** [comment]
haha, having some issues with linter @zanellia? I guess it does need some getting used to.. :P Greetings from Boston!

**Comment by zanellia** [comment]
Good to know that you all receive emails when I push to my repo as long as the pull request is open...I need some privacy here =) AND poor Travis has tried to merge all my commits

**Comment by zanellia** [comment]
Need to restore timings in sim_erk_integrator.c and warning-errors in CMakeLists.txt before merging.

**Pull request merged**
