### PR TITLE
fixing bugs in acados_solver.in.c - C_e not set, wrong D and C dims

### PR DESCRIPTION
**Pull request by zanellia**
The first one was introduced recently, how did it not break the tests?

### CODE REVIEW

**Comment by zanellia** [comment]
> The first one was introduced recently, how did it not break the tests?

I see, the solution of the PMSM example is not checked of course.

**Comment by FreyJo** [comment]
> The first one was introduced recently, how did it not break the tests?

Right, the C_e probably got lost, while restructuring!
I just checked the last release, there the dimensions of D and C are also wrong.

**Comment by FreyJo** [comment]
Yes, adding a test for the general linear constraint would be great!

> > The first one was introduced recently, how did it not break the tests?
> 
> I see, the solution of the PMSM example is not checked of course.

Adding a test for the general linear constraints would be great!

**Comment by zanellia** [comment]
> > The first one was introduced recently, how did it not break the tests?
> 
> Right, the C_e probably got lost, while restructuring!
> I just checked the last release, there the dimensions of D and C are also wrong.

I know, that's why I said the first one :) The second one was never detected because the only example that makes use of the polytopic constraints at t=T had n_x = n_u.

**Comment by FreyJo** [comment]
Ah good to know :)
I was not sure about "first", cause I looked mainly at the diff.

**Pull request merged**
